version: 2.1
jobs:
  build_test:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run: 
          name: Install npm dependencies
          command: npm install

  build_docker_image:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: docker build -t chumanilalasa/circleci:latest .
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: docker push chumanilalasa/circle:latest
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_test
      - build_docker_image:
          requires:
            - build_test